### PR TITLE
Update Kbank Pattern

### PR DESCRIPTION
**Pull request by isudnop**
🆙  Add 1 TH  Kbank SMS deposit pattern

### CODE REVIEW

**Review by dtinth — CHANGES_REQUESTED** [review]
Can you also add a testcase in `test/sms_testcase.csv`?

https://github.com/dtinth/transaction-parser-th/blob/master/test/sms_testcase.csv

This helps ensure that when the library gets refactored, all of these cases still works as expected.

**Comment by isudnop** [comment]
@dtinth sure, no problem

**Comment by isudnop** [comment]
is it possible to convert buddhist calendar to Anno Domini?
my SMS from Kbank got date pattern like 18/11/61 which exactly the same as english version that you put in test case.

**Comment by dtinth** [comment]
Yes: You can create a new “placeholder matcher”.

Since it is anticipated that SMS text from different vendors will have different date format, like, 2018-11-19, 19/11/2561, 19 พ.ย. 61, the concept of “placeholder matcher” is introduced to enable this flexibility of parsing things.

Here’s how `kbank_date` is defined...

https://github.com/dtinth/transaction-parser-th/blob/e463e53e497b395f093eb82750bd346619a1cb84/src/PatternMatcher.ts#L50-L56

You can create a new placeholder matcher for, e.g. `kbank_date_bc` and make it convert BC to AD. (AD is used following ISO date standards)

**Pull request closed without merging**
